const Card = [
    {
        id: 1,
        Title: "Snapchat Landing Page",
        Type: "Clone",
        Description: "This website is a clone of the snapchat landing page",
        Image: "https://i.pinimg.com/564x/09/6a/b0/096ab0f9ba12085c5078b99a26d694dd.jpg",
        Code: "",
        Demo: "https://dev-rook-snapchat-clone.netlify.app",
        Status: "Unfinished",
    },
    {
        id: 2,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 3,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 4,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 5,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 6,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 7,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 8,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 9,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
    {
        id: 10,
        Title: "",
        Type: "",
        Discription: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "",
    },
]


export default Card