const Card = [
    {
        id: 1,
        Title: "Snapchat Landing Page 👻",
        Type: "Clone",
        Description: "This website is a clone of the snapchat landing page",
        Image: "https://i.pinimg.com/564x/0e/66/fe/0e66fe66f9778deec219a4fc4ad83c56.jpg",
        Code: "",
        Demo: "https://dev-rook-snapchat-clone.netlify.app",
        Status: "Unfinished",
    },
    {
        id: 2,
        Title: "Montego Bay Yacht Club 🚤",
        Type: "Solo Build",
        Description: "A newer and stylish website for the current MYBC website",
        Image: "https://i.pinimg.com/564x/4a/3c/54/4a3c54710d0bb6f32cf7275f9ec7f9bf.jpg",
        Code: "",
        Demo: "",
        Status: "Development",
    },
    {
        id: 3,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 4,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 5,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 6,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 7,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 8,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 9,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
    {
        id: 10,
        Title: "",
        Type: "",
        Description: "",
        Image: "",
        Code: "",
        Demo: "",
        Status: "Develpment",
    },
]


export default Card